finished (for now) conversion of Cbc to autotools

diff --git a/Vol/configure b/Vol/configure
--- a/Vol/configure
+++ b/Vol/configure
@@ -473,7 +473,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE COIN_DEBUG_TRUE COIN_DEBUG_FALSE CXXDEFS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake BUILDTOOLSDIR AUX_DIR HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE MAINTAINER_SMALL_TRUE MAINTAINER_SMALL_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL pkg_lib_dir pkg_include_dir pkg_bin_dir COINBASESRCDIR COINBASEOBJDIR COIN_HAS_COINBASE_TRUE COIN_HAS_COINBASE_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE COIN_DEBUG_TRUE COIN_DEBUG_FALSE CXXDEFS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake BUILDTOOLSDIR AUX_DIR HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE MAINTAINER_SMALL_TRUE MAINTAINER_SMALL_FALSE CC CFLAGS ac_ct_CC CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL pkg_lib_dir pkg_include_dir pkg_bin_dir COINBASESRCDIR COINBASEOBJDIR COIN_HAS_COINBASE_TRUE COIN_HAS_COINBASE_FALSE VOLSRCDIR VOLOBJDIR COIN_HAS_VOL_TRUE COIN_HAS_VOL_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19551,6 +19551,50 @@ fi
 echo "$as_me:$LINENO: result: $coin_has_coinbase" >&5
 echo "${ECHO_T}$coin_has_coinbase" >&6
 
+echo "$as_me:$LINENO: checking for COIN project Vol" >&5
+echo $ECHO_N "checking for COIN project Vol... $ECHO_C" >&6
+
+# First check, if the sub-project is actually available (ToDo: allow
+# other locations)
+
+coin_has_vol=unavailable
+if test $PACKAGE_TARNAME = vol; then
+  coin_has_vol=.
+else
+  if test -d $srcdir/../Vol; then
+    coin_has_vol=../Vol
+  fi
+fi
+
+if test $coin_has_vol != unavailable; then
+  # Set the #define if the component is available
+
+cat >>confdefs.h <<\_ACEOF
+#define COIN_HAS_VOL 1
+_ACEOF
+
+
+  # Set the variables for source and object code location
+
+  VOLSRCDIR=`cd $srcdir/$coin_has_vol; pwd`
+
+  VOLOBJDIR=`pwd`/$coin_has_vol
+fi
+
+  # Define the Makefile conditional
+
+
+if test $coin_has_vol != unavailable; then
+  COIN_HAS_VOL_TRUE=
+  COIN_HAS_VOL_FALSE='#'
+else
+  COIN_HAS_VOL_TRUE='#'
+  COIN_HAS_VOL_FALSE=
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_vol" >&5
+echo "${ECHO_T}$coin_has_vol" >&6
+
 
 ##############################################################################
 #                   Finishing up by writing all the output                   #
@@ -19717,6 +19761,13 @@ if test -z "${COIN_HAS_COINBASE_TRUE}" && test -z "${COIN_HAS_COINBASE_FALSE}"; 
   { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_COINBASE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COIN_HAS_COINBASE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${COIN_HAS_VOL_TRUE}" && test -z "${COIN_HAS_VOL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_VOL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_VOL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20344,6 +20395,10 @@ s,@COINBASESRCDIR@,$COINBASESRCDIR,;t t
 s,@COINBASEOBJDIR@,$COINBASEOBJDIR,;t t
 s,@COIN_HAS_COINBASE_TRUE@,$COIN_HAS_COINBASE_TRUE,;t t
 s,@COIN_HAS_COINBASE_FALSE@,$COIN_HAS_COINBASE_FALSE,;t t
+s,@VOLSRCDIR@,$VOLSRCDIR,;t t
+s,@VOLOBJDIR@,$VOLOBJDIR,;t t
+s,@COIN_HAS_VOL_TRUE@,$COIN_HAS_VOL_TRUE,;t t
+s,@COIN_HAS_VOL_FALSE@,$COIN_HAS_VOL_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
