final instdir commits for tonight

diff --git a/Vol/configure b/Vol/configure
--- a/Vol/configure
+++ b/Vol/configure
@@ -20489,13 +20489,16 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_coinutils=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   COINUTILSINSTDIR=`cd $withval; pwd`
+		   if test -r $withval/include/coin/CoinTime.hpp; then
+                        coin_has_coinutils=installed
+			COINUTILSINSTDIR=`cd $withval; pwd`
+                      fi
+
 fi;
     fi
 
@@ -20558,8 +20561,35 @@ if test $coin_has_coinutils = installed; then
   echo "$as_me:$LINENO: result: installed in $COINUTILSINSTDIR" >&5
 echo "${ECHO_T}installed in $COINUTILSINSTDIR" >&6
   # Check for header
+  tmp=$COINUTILSINSTDIR/include/coin
+                  echo "$as_me:$LINENO: checking whether header CoinTime.hpp is available in $tmp" >&5
+echo $ECHO_N "checking whether header CoinTime.hpp is available in $tmp... $ECHO_C" >&6
+                  if test -r $tmp/CoinTime.hpp; then
+		    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+		  else
+		    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		    { { echo "$as_me:$LINENO: error: Header CoinTime.hpp not available in CoinUtils installation directory" >&5
+echo "$as_me: error: Header CoinTime.hpp not available in CoinUtils installation directory" >&2;}
+   { (exit 1); exit 1; }; }
+		  fi
 
   # Check for library (this is not qo reliable)
+  tmp=$COINUTILSINSTDIR/lib
+                  echo "$as_me:$LINENO: checking whether library libCoinUtils.* is available in $tmp" >&5
+echo $ECHO_N "checking whether library libCoinUtils.* is available in $tmp... $ECHO_C" >&6
+		  bla=`ls $tmp/libCoinUtils.* 2>/dev/null | head -n 1`
+		  if test x"$bla" = x; then
+		    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+		    { { echo "$as_me:$LINENO: error: Library libCoinUtils.* not available in CoinUtils installation directory" >&5
+echo "$as_me: error: Library libCoinUtils.* not available in CoinUtils installation directory" >&2;}
+   { (exit 1); exit 1; }; }
+		  else
+		    echo "$as_me:$LINENO: result: found $bla" >&5
+echo "${ECHO_T}found $bla" >&6
+		  fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_coinutils" >&5
@@ -20654,13 +20684,14 @@ fi;
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
 if test "${with_coin_instdir+set}" = set; then
   withval="$with_coin_instdir"
-  coin_has_vol=installed
-		   if test -d "$withval"; then : ; else
+  if test -d "$withval"; then : ; else
 		     { { echo "$as_me:$LINENO: error: argument for --with-coin-instdir not a directory" >&5
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-                   VOLINSTDIR=`cd $withval; pwd`
+		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
+echo "$as_me: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
+
 fi;
     fi
 
