a few bugfixes for instdir

diff --git a/Vol/configure b/Vol/configure
--- a/Vol/configure
+++ b/Vol/configure
@@ -20494,11 +20494,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   if test -r $withval/include/coin/CoinTime.hpp; then
-                        coin_has_coinutils=installed
-			COINUTILSINSTDIR=`cd $withval; pwd`
-                      fi
-
+		   if test -r $withval/share/doc/coin/CoinUtils/README; then
+		     coin_has_coinutils=installed
+		     COINUTILSINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -20560,40 +20559,30 @@ fi
 if test $coin_has_coinutils = installed; then
   echo "$as_me:$LINENO: result: installed in $COINUTILSINSTDIR" >&5
 echo "${ECHO_T}installed in $COINUTILSINSTDIR" >&6
-  # Check for header
-  tmp=$COINUTILSINSTDIR/include/coin
-                  echo "$as_me:$LINENO: checking whether header CoinTime.hpp is available in $tmp" >&5
-echo $ECHO_N "checking whether header CoinTime.hpp is available in $tmp... $ECHO_C" >&6
-                  if test -r $tmp/CoinTime.hpp; then
-		    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-		  else
-		    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-		    { { echo "$as_me:$LINENO: error: Header CoinTime.hpp not available in CoinUtils installation directory" >&5
-echo "$as_me: error: Header CoinTime.hpp not available in CoinUtils installation directory" >&2;}
-   { (exit 1); exit 1; }; }
-		  fi
+  if test -r $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README; then
 
-  # Check for library (this is not qo reliable)
-  tmp=$COINUTILSINSTDIR/lib
-                  echo "$as_me:$LINENO: checking whether library libCoinUtils.* is available in $tmp" >&5
-echo $ECHO_N "checking whether library libCoinUtils.* is available in $tmp... $ECHO_C" >&6
-		  bla=`ls $tmp/libCoinUtils.* 2>/dev/null | head -n 1`
-		  if test x"$bla" = x; then
-		    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-		    { { echo "$as_me:$LINENO: error: Library libCoinUtils.* not available in CoinUtils installation directory" >&5
-echo "$as_me: error: Library libCoinUtils.* not available in CoinUtils installation directory" >&2;}
+  :
+else
+  { { echo "$as_me:$LINENO: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&5
+echo "$as_me: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&2;}
    { (exit 1); exit 1; }; }
-		  else
-		    echo "$as_me:$LINENO: result: found $bla" >&5
-echo "${ECHO_T}found $bla" >&6
-		  fi
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_coinutils" >&5
 echo "${ECHO_T}$coin_has_coinutils" >&6
+  if test $coin_has_coinutils != notGiven &&
+     test $coin_has_coinutils != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of CoinUtils" >&5
+echo $ECHO_N "checking for source code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSSRCDIR" >&5
+echo "${ECHO_T}$COINUTILSSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of CoinUtils" >&5
+echo $ECHO_N "checking for object code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSOBJDIR" >&5
+echo "${ECHO_T}$COINUTILSOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Vol" >&5
@@ -20689,9 +20678,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Vol with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Vol/README; then
+		     coin_has_vol=installed
+		     VOLINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -20753,13 +20743,30 @@ fi
 if test $coin_has_vol = installed; then
   echo "$as_me:$LINENO: result: installed in $VOLINSTDIR" >&5
 echo "${ECHO_T}installed in $VOLINSTDIR" >&6
-  # Check for header
+  if test -r $VOLINSTDIR/share/doc/coin/Vol/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $VOLINSTDIR/share/doc/coin/Vol/README should be available if Vol is installed" >&5
+echo "$as_me: error: $VOLINSTDIR/share/doc/coin/Vol/README should be available if Vol is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_vol" >&5
 echo "${ECHO_T}$coin_has_vol" >&6
+  if test $coin_has_vol != notGiven &&
+     test $coin_has_vol != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Vol" >&5
+echo $ECHO_N "checking for source code location of Vol... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $VOLSRCDIR" >&5
+echo "${ECHO_T}$VOLSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Vol" >&5
+echo $ECHO_N "checking for object code location of Vol... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $VOLOBJDIR" >&5
+echo "${ECHO_T}$VOLOBJDIR" >&6
+  fi
 fi
 
 
